'\" t
.\"     Title: udevd
.\"    Author: Kay Sievers <kay@vrfy.org>
.\" Generator: DocBook XSL Stylesheets v1.78.0 <http://docbook.sf.net/>
.\"      Date: 10/31/2014
.\"    Manual: udevd
.\"    Source: udev
.\"  Language: English
.\"
.TH "UDEVD" "8" "" "udev" "udevd"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
udevd \- Device event managing daemon
.SH "SYNOPSIS"
.PP
udevd
.HP \w'\fB/sbin/udevd\fR\ 'u
\fB/sbin/udevd\fR [\fB\-\-daemon\fR] [\fB\-\-debug\fR] [\fB\-\-children\-max=\fR] [\fB\-\-exec\-delay=\fR] [\fB\-\-resolve\-names=early|late|never\fR] [\fB\-\-version\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
\fBudevd\fR
listens to kernel uevents\&. For every event, udevd executes matching instructions specified in udev rules\&. See
\fBudev\fR(7)\&.
.PP
The behavior of the running daemon can be changed dynamically with
\fBudevadm control\fR, or configured using
\fBudev.conf\fR(5)\&.
.SH "OPTIONS"
.PP
\fB\-\-daemon\fR
.RS 4
Detach and run in the background\&.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Print debug messages to stderr\&.
.RE
.PP
\fB\-\-children\-max=\fR
.RS 4
Limit the number of events executed in parallel\&.
.RE
.PP
\fB\-\-exec\-delay=\fR
.RS 4
Delay the execution of RUN instruction by the given number of seconds\&. This option might be useful when debugging system crashes during coldplug caused by loading non\-working kernel modules\&.
.RE
.PP
\fB\-\-resolve\-names=\fR
.RS 4
Specify when udevd should resolve names of users and groups\&. When set to
\fBearly\fR
(the default) names will be resolved when the rules are parsed\&. When set to
\fBlate\fR
names will be resolved for every event\&. When set to
\fBnever\fR
names will never be resolved and all devices will be owned by root\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version number\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print help text\&.
.RE
.SH "ENVIRONMENT"
.PP
\fI$UDEV_LOG=\fR
.RS 4
Set the logging priority\&.
.RE
.SH "KERNEL COMMAND LINE"
.PP
Parameters starting with "rd\&." will be read when
\fBudevd\fR
is used in an initrd\&.
.PP
\fIudev\&.log\-priority=\fR, \fIrd\&.udev\&.log\-priority=\fR
.RS 4
Set the logging priority\&.
.RE
.PP
\fIudev\&.children\-max=\fR, \fIrd\&.udev\&.children\-max=\fR
.RS 4
Limit the number of events executed in parallel\&.
.RE
.PP
\fIudev\&.exec\-delay=\fR, \fIrd\&.udev\&.exec\-delay=\fR
.RS 4
Delay the execution of RUN instruction by the given number of seconds\&. This option might be useful when debugging system crashes during coldplug caused by loading non\-working kernel modules\&.
.RE
.PP
\fInet\&.ifnames=\fR
.RS 4
Network interfaces are renamed to give them predictable names when possible\&. It is enabled by default, specifying 0 disables it\&.
.RE
.SH "SEE ALSO"
.PP

\fBudev.conf\fR(5),
\fBudev\fR(7),
\fBudevadm\fR(8)
